// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"

	xpcommon "github.com/crossplane/crossplane-runtime/v2/apis/common"
	resource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
)

// GetProviderConfigReference of this NamespacedProviderConfigUsage.
func (p *NamespacedProviderConfigUsage) GetProviderConfigReference() xpcommon.ProviderConfigReference {
	return p.ProviderConfigReference
}

// GetResourceReference of this NamespacedProviderConfigUsage.
func (p *NamespacedProviderConfigUsage) GetResourceReference() xpcommon.TypedReference {
	return p.ResourceReference
}

// SetProviderConfigReference of this NamespacedProviderConfigUsage.
func (p *NamespacedProviderConfigUsage) SetProviderConfigReference(r xpcommon.ProviderConfigReference) {
	p.ProviderConfigReference = r
}

// SetResourceReference of this NamespacedProviderConfigUsage.
func (p *NamespacedProviderConfigUsage) SetResourceReference(r xpcommon.TypedReference) {
	p.ResourceReference = r
}

// DeepCopyObject implements runtime.Object.
func (p *NamespacedProviderConfigUsage) DeepCopyObject() runtime.Object {
	if c := p.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy creates a deep copy of NamespacedProviderConfigUsage.
func (p *NamespacedProviderConfigUsage) DeepCopy() *NamespacedProviderConfigUsage {
	if p == nil {
		return nil
	}
	out := new(NamespacedProviderConfigUsage)
	*out = *p
	out.TypeMeta = p.TypeMeta
	p.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.TypedProviderConfigUsage = p.TypedProviderConfigUsage
	return out
}

// DeepCopyObject implements runtime.Object for NamespacedProviderConfigUsageList.
func (p *NamespacedProviderConfigUsageList) DeepCopyObject() runtime.Object {
	if c := p.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy creates a deep copy of NamespacedProviderConfigUsageList.
func (p *NamespacedProviderConfigUsageList) DeepCopy() *NamespacedProviderConfigUsageList {
	if p == nil {
		return nil
	}
	out := new(NamespacedProviderConfigUsageList)
	*out = *p
	out.TypeMeta = p.TypeMeta
	p.ListMeta.DeepCopyInto(&out.ListMeta)
	if p.Items != nil {
		out.Items = make([]NamespacedProviderConfigUsage, len(p.Items))
		for i := range p.Items {
			out.Items[i] = p.Items[i]
			p.Items[i].ObjectMeta.DeepCopyInto(&out.Items[i].ObjectMeta)
		}
	}
	return out
}

// GetItems of this NamespacedProviderConfigUsageList.
func (p *NamespacedProviderConfigUsageList) GetItems() []resource.ProviderConfigUsage {
	items := make([]resource.ProviderConfigUsage, len(p.Items))
	for i := range p.Items {
		items[i] = &p.Items[i]
	}
	return items
}
