---
apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kind
  annotations:
    meta.crossplane.io/maintainer: The provider-kind authors
    meta.crossplane.io/source: github.com/humoflife/provider-kind
    meta.crossplane.io/description: |
      A native Crossplane provider for KIND (Kubernetes IN Docker).
      Manages KIND clusters as managed resources without Terraform.
    meta.crossplane.io/readme: |
      provider-kind manages KIND (Kubernetes IN Docker) clusters as Crossplane
      managed resources. It uses the KIND Go library to create and delete
      clusters via the host Docker daemon — no cloud credentials required.

      Supported resources:
        - kind.crossplane.io/v1alpha1/Cluster  (cluster-scoped, LegacyManaged)
        - kind.m.crossplane.io/v1alpha1/Cluster (namespaced, ModernManaged)

      IMPORTANT: the provider pod must be able to reach the host Docker daemon.
      Apply the DeploymentRuntimeConfig from examples/runtime-config.yaml before
      installing the provider, and reference it in the Provider spec:

        spec:
          runtimeConfigRef:
            apiVersion: pkg.crossplane.io/v1beta1
            kind: DeploymentRuntimeConfig
            name: provider-kind

      See https://github.com/humoflife/provider-kind for full documentation.
